### PR TITLE
Release 8.0.0

### PR DESCRIPTION
**Pull request by hobbitronics**
# Includes
- https://github.com/silinternational/ui-components/pull/173
- https://github.com/silinternational/ui-components/pull/172

Question: Should this be a breaking change? The original release was meant for the consumer to use material 14, but since I forgot to change the peer deps npm was requiring version 13. That means the previous release change was not really breaking, although there were other breaking changes in the release.

### CODE REVIEW

**Comment by forevermatt** [comment]
> Question: Should this be a breaking change? The original release was meant for the consumer to use material 14, but since I forgot to change the peer deps npm was requiring version 13. That means the previous release change was not really breaking, although there were other breaking changes in the release.

Unfortunately, I think it probably would be better to publish this a(nother) breaking change, since going from 7.0.0 to this release would break things. You could make a case that this is a bugfix of that accidental peer-deps issue that was supposed to be changed in the previous release, so it could go either way.

As a separate note, the package.json file still has a very old version number in it for this library. Let's either update that or remove it.

**Review by forevermatt — APPROVED** [review]
Approving, with the understanding that the release number might (or might not) be changed from 7.0.1 to 8.0.0

**Comment by hobbitronics** [comment]
> > Question: Should this be a breaking change? The original release was meant for the consumer to use material 14, but since I forgot to change the peer deps npm was requiring version 13. That means the previous release change was not really breaking, although there were other breaking changes in the release.
> 
> Unfortunately, I think it probably would be better to publish this a(nother) breaking change, since going from 7.0.0 to this release would break things. You could make a case that this is a bugfix of that accidental peer-deps issue that was supposed to be changed in the previous release, so it could go either way.
> 
> As a separate note, the package.json file still has a very old version number in it for this library. Let's either update that or remove it.

That is because semantic-release updates the version in the main branch only. Yes, we could change it in develop, or remove it, but it won't have an effect downstream and I don't want to risk removing it as I'm not confident that won't have some kind of unanticipated side effect. I think I will go with the breaking change to 8. Thanks for your input.

**Pull request merged**
