### PR TITLE
Release 10.4.0

### PR DESCRIPTION
**Pull request by hobbitronics**
- Add lowContrast to DataRowItem

### CODE REVIEW

**Review by merchako — APPROVED** [review]
In general I'm cool with this (as I said in the original PR). Now that it's coming time to add it use it in external projects, I'm wondering if `lowConstrast` might be a bit too literal.

MDC uses the word "emphasis" which may serve us better.

> High-emphasis text has an opacity of 87%
Medium-emphasis text and hint text have opacities of 60%
[Low-emphasis] Disabled text has an opacity of 38%

Would it be more sustainable to have:
```ts
emphasis: "high" | "medium" | "low"
```

And eventually we could add
```ts
emphasis: "high" | "medium" | "low" | "disabled" | "error"
```
where `"low" ~= "disabled"`

I'm really fine either way, but I want to bring it up now in case we put ourselves in a bind later.

image


https://m2.material.io/design/color/text-legibility.html#text-backgrounds

**Comment by hobbitronics** [comment]
@merchako I am reluctant to use disabled as that has other implications than color, which we don't address here. I also don't feel the need to add other emphasis colors at the moment. What I do wonder is should we change the color variable here to match the disabled color and if you have an idea how to use the primary text color with 38% opacity.

**Comment by hobbitronics** [comment]
I am going to stick with what we have and we can change if needed in the future.

**Pull request merged**
