### PR TITLE
CVR-674 Improve Button typography

### PR DESCRIPTION
**Pull request by merchako**
[CVR-674](https://itse.youtrack.cloud/issue/CVR-674) Improve Button typography

### CODE REVIEW

**Review by hobbitronics — CHANGES_REQUESTED** [review]
This needs a commit message that will trigger a release. You can rebase, or just push an empty commit. The question I have is, will it be a major or minor release?

**Comment by merchako** [comment]
> You can rebase, or just push an empty commit. The question I have is, will it be a major or minor release?

It's a minor change, so I rebased the commit message to prepend `feat(Button):`.

**Review by hobbitronics — CHANGES_REQUESTED** [review]
I've just noticed this change is to the stories app's typography. To get the results you want you should make these changes to the consumer of the library _typography file.

**Comment by hobbitronics** [comment]
> > You can rebase, or just push an empty commit. The question I have is, will it be a major or minor release?
> 
> It's a minor change, so I rebased the commit message to prepend `feat(Button):`.

I recommend to close this as it's really a change that should be made in cover, as these changes are to the storybook app.

**Comment by merchako** [comment]
@hobbitronics , oh. I see what you mean.

Would it be okay if I added these changes to _ui-components_ elsewhere? such as
* a new __typography.scss_
* components/mdc/_index.scss
* components/global.scss

The point of this branch is to improve button-like typography by *reducing* custom letter spacing from upstream. I don't think any of our products would benefit from the extreme as-is letter spacing, so I'd rather not depend on each consumer of _ui-components_ to do this overwrite.

**Comment by hobbitronics** [comment]
> @hobbitronics , oh. I see what you mean.
> 
> Would it be okay if I added these changes to _ui-components_ elsewhere? such as
> 
> * a new __typography.scss_
> * components/mdc/_index.scss
> * components/global.scss
> 
> The point of this branch is to improve button-like typography by _reducing_ custom letter spacing from upstream. I don't think any of our products would benefit from the extreme as-is letter spacing, so I'd rather not depend on each consumer of _ui-components_ to do this overwrite.

Do you know where the extreme letter spacing is coming from? I just want to test this and make sure it works as expected before merging. Also can we leave CVR out of the commits here?

**Comment by merchako** [comment]
> Do you know where the extreme letter spacing is coming from? I just want to test this and make sure it works as expected before merging. 

The extreme letter spacing must be coming from MDC, because there aren't any other rules affecting `letter-spacing` within _cover-ui_ or _ui-components_.  

I believe it's coming from MDC via `.mdc-button*` 

```css
mdc-button,
mdc-button--raised  /* and probably all the button classes */
{
  letter-spacing: 
    var(--mdc-protected-button-label-text-tracking, /* unset */
      var(--mdc-typography-button-letter-spacing,  /* unset */
        0.0892857143em)) /* ← where it comes from */

}
```

> Also can we leave CVR out of the commits here?

I'm fine with this. This problem emerged from Cover, so I included it. But however you want to name it is fine with me.

**Comment by hobbitronics** [comment]
> > Do you know where the extreme letter spacing is coming from? I just want to test this and make sure it works as expected before merging.
> 
> The extreme letter spacing must be coming from MDC, because there aren't any other rules affecting `letter-spacing` within _cover-ui_ or _ui-components_.
> 
> I pointed a web inspector at Storybook, and I believe it's coming from MDC via `.mdc-button*`
> 
> ```css
> mdc-button,
> mdc-button--raised  /* and probably all the button classes */
> {
>   letter-spacing: 
>     var(--mdc-protected-button-label-text-tracking, /* unset */
>       var(--mdc-typography-button-letter-spacing,  /* unset */
>         0.0892857143em)) /* ← where it comes from */
> 
> }
> ```
> 
> > Also can we leave CVR out of the commits here?
> 
> I'm fine with this. This problem emerged from Cover, so I included it. But however you want to name it is fine with me.

Thanks for looking into this. I wonder if it is an issue with mdc or maybe it could be related to us not pulling in any google fonts within ui-components? I tried to leave all that up to the consumer, but it has been difficult to get fonts working as you can remember.

**Review by hobbitronics — CHANGES_REQUESTED** [review]
While I don't have a problem with these default styles, the consumer should be defining and making the api call to get their own typography and applying it to the entire app, not just the mdc components. I tested this in Cover and it seems to be overridden by the typography we define there, meaning this won't solve Cover's problem.

**Comment by merchako** [comment]
Per our conversation, I'm leaving this PR to you to use as you please, @hobbitronics .

**Pull request closed without merging**
