### PR TITLE
Release 3.1.0

### PR DESCRIPTION
**Pull request by forevermatt**
### Added
- Dispatch 'populated' event when a Select's options are populated. Useful for knowing when it's safe to set the initial selectedID value.

### Fixed
- Updated npm dependencies.

### CODE REVIEW

**Review by hobbitronics — APPROVED** [review]
Looks good

**Review by Schparky — APPROVED** [review]

**Review by hobbitronics — COMMENTED** [review]
Before you merge, we need to verify the updating dependencies didn't break the storybook deployment. I still haven't figured out which one did that last time I ran npm updated.

**Review by hobbitronics — CHANGES_REQUESTED** [review]
Storybook still appears to online. I am adding the new event to the Select.stories.svelte file to be part of this release.

**Review by hobbitronics — APPROVED** [review]
Looks like builds are still coming through fine. I see the console.log I added to the story.

**Pull request merged**
