### PR TITLE
Release 9.0.0

### PR DESCRIPTION
**Pull request by hobbitronics**
- Update README
- improve Card Story
- Remove window reference on Menu
- Add currentUrl prop to Menu and Menu story
- Update index.d.ts

### CODE REVIEW

**Review by Schparky — APPROVED** [review]

**Comment by Schparky** [comment]
Just thinking for a minute, that major version changes should come with some instructions on what a user of this library would need to do to make the upgrade. That could be in the README or in the release itself or both.

**Comment by hobbitronics** [comment]
> Just thinking for a minute, that major version changes should come with some instructions on what a user of this library would need to do to make the upgrade. That could be in the README or in the release itself or both.
In the commit that contains
"BREAKING_CHANGES: ..." It will add to the changelog. It only gets updated in the main branch though.

**Comment by Schparky** [comment]
> > Just thinking for a minute, that major version changes should come with some instructions on what a user of this library would need to do to make the upgrade. That could be in the README or in the release itself or both.
> > The commit that contains
> > "feat(Menu): remove focus of menuItem based on path. Add currentUrl story
> > BREAKING CHANGE: remove checking of current path to focus menu item" It will be added to the changelog. It only gets updated in the main branch though.

Putting words in my mouth, I see, lol. (Your new text is prefixed with `>`)

**Pull request merged**
