### PR TITLE
Feature/update prettier

### PR DESCRIPTION
**Pull request by merchako**
Upgrade Prettier to v3.0.3
Necessary to use [tailwindlabs/prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss) in codebases that also want to use Tailwind CSS.

Note: The code changes are from the _old_ Prettier and would have happened anyway if we'd run `npm run format-all`. The new Prettier didn't introduce any changes to our code upon formatting.

### CODE REVIEW

**Review by hobbitronics — APPROVED** [review]
Since this is a peerDependency I don't see how it was causing a problem with the consumer, but these changes good either way. The only potential issue is the CHANGELOG won't follow these as updates to it are autogenerated to semantic release.

**Comment by forevermatt** [comment]
@hobbitronics Is it okay if I go ahead and delete the `feature/update-prettier` branch now that this has been merged?

**Comment by merchako** [comment]
sure 🙂

**Pull request merged**
